name: CZ3002
channels:
  - conda-forge
dependencies:
  - python=3.8
  - django=3.2.6
  - yapf=0.31.0
  - django-extensions=3.1.3
  - django-cors-headers=3.9.0
  - Werkzeug=2.0.1
  - pyOpenSSL=20.0.1
  - psycopg2=2.9.1
  - argon2_cffi=19.1.0
